Fix `std::command`-related panicking by switching to waitid()… kinda… sorta
thread 'main' panicked at 'wait() should either return Ok or panic', …/src/libstd/sys/unix/process/process_unix.rs:74

…
wait4(2576, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 2576
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2576, si_uid=0, si_status=1, si_utime=0, si_stime=0} ---
wait4(-1, 0x7ffe70195600, WNOHANG, NULL) = -1 ECHILD (No child processes)
…

…
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2577, si_uid=0, si_status=1, si_utime=0, si_stime=0} ---
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], WNOHANG, NULL) = 2577
wait4(-1, 0x7ffe70195600, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn({mask=[]})                 = 8
wait4(2577, 0x7ffe70195d98, 0, NULL)    = -1 ECHILD (No child processes)
write(2, "thread '", 8)                 = 8
write(2, "main", 4)                     = 4
write(2, "' panicked at '", 15)         = 15
…